<?xml version="1.0" encoding="utf-8"?><Database Name="LanguageLearningApp" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-MLLONH5;Initial Catalog=LanguageLearningApp;Integrated Security=True" SettingsObjectName="WpfApp2.Properties.Settings" SettingsPropertyName="LanguageLearningAppConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AdminAccessLogs" Member="AdminAccessLogs">
    <Type Name="AdminAccessLog">
      <Column Name="LogID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AdministratorID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccessDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ActionDescription" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_UserFeedback" Member="UserFeedbacks" ThisKey="UserID" OtherKey="UserID" Type="UserFeedback" />
      <Association Name="User_ProgressHistory" Member="ProgressHistories" ThisKey="UserID" OtherKey="UserID" Type="ProgressHistory" />
      <Association Name="User_Progress" Member="Progresses" ThisKey="UserID" OtherKey="UserID" Type="Progress" />
      <Association Name="User_Lesson" Member="Lessons" ThisKey="UserID" OtherKey="CreatorUserID" Type="Lesson" />
      <Association Name="User_Favorite" Member="Favorites" ThisKey="UserID" OtherKey="UserID" Type="Favorite" />
    </Type>
  </Table>
  <Table Name="dbo.UserFeedback" Member="UserFeedbacks">
    <Type Name="UserFeedback">
      <Column Name="FeedbackID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FeedbackText" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SubmissionDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="User_UserFeedback" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QuizQuestions" Member="QuizQuestions">
    <Type Name="QuizQuestion">
      <Column Name="QuestionID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LessonID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QuestionText" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="QuizQuestion_QuizAnswer" Member="QuizAnswers" ThisKey="QuestionID" OtherKey="QuestionID" Type="QuizAnswer" />
    </Type>
  </Table>
  <Table Name="dbo.QuizAnswers" Member="QuizAnswers">
    <Type Name="QuizAnswer">
      <Column Name="AnswerID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QuestionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AnswerText" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="IsCorrect" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="QuizQuestion_QuizAnswer" Member="QuizQuestion" ThisKey="QuestionID" OtherKey="QuestionID" Type="QuizQuestion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProgressHistory" Member="ProgressHistories">
    <Type Name="ProgressHistory">
      <Column Name="HistoryID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LessonID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CompletionDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="User_ProgressHistory" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
      <Association Name="Lesson_ProgressHistory" Member="Lesson" ThisKey="LessonID" OtherKey="LessonID" Type="Lesson" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Progress" Member="Progresses">
    <Type Name="Progress">
      <Column Name="ProgressID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LessonID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CompletionDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="User_Progress" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
      <Association Name="Lesson_Progress" Member="Lesson" ThisKey="LessonID" OtherKey="LessonID" Type="Lesson" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Lessons" Member="Lessons">
    <Type Name="Lesson">
      <Column Name="LessonID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LessonTitle" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LessonContent" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CreatorUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Lesson_ProgressHistory" Member="ProgressHistories" ThisKey="LessonID" OtherKey="LessonID" Type="ProgressHistory" />
      <Association Name="Lesson_Progress" Member="Progresses" ThisKey="LessonID" OtherKey="LessonID" Type="Progress" />
      <Association Name="Lesson_Favorite" Member="Favorites" ThisKey="LessonID" OtherKey="LessonID" Type="Favorite" />
      <Association Name="User_Lesson" Member="User" ThisKey="CreatorUserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Favorites" Member="Favorites">
    <Type Name="Favorite">
      <Column Name="FavoriteID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LessonID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Lesson_Favorite" Member="Lesson" ThisKey="LessonID" OtherKey="LessonID" Type="Lesson" IsForeignKey="true" />
      <Association Name="User_Favorite" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>